@baseUrl = http://127.0.0.1:5001/api
@token = LOOK-SECURE-TOKEN-2024

### 1. List All Devices
POST {{baseUrl}}/list_devices
X-API-TOKEN: {{token}}

### 2. Add New Device
POST {{baseUrl}}/add_device
X-API-TOKEN: {{token}}
Content-Type: application/json

{
    "device_id": "ID_001",
    "device_name": "Sensor suhu",
    "type_device": "temperature",
    "status": 1
}

### 3. Update Device
POST {{baseUrl}}/update_device
X-API-TOKEN: {{token}}
Content-Type: application/json

{
    "device_id": "ID_001",
    "device_name": "Sensor suhu Updated",
    "type_device": "temperature",
    "status": 0
}

### 4. Delete Device
POST {{baseUrl}}/delete_device
X-API-TOKEN: {{token}}
Content-Type: application/json

{
    "device_id": "ID_001"
}

### 5. Get Data Records
GET {{baseUrl}}/records
X-API-TOKEN: {{token}}
